### ISSUE TITLE
This tor feature is secure?

### ISSUE THREAD

**Issue by broland07** [jlund/streisand-discussions#100]
Hello guys!

I have a question, that is tor feature is secure? In iftop i see that communicate with ru servers and yui.cat.
Is it secure? I know that the connection are secure but i hosted is Digitalocean and i freak to turned off my vps.

**Comment by nickolasclarke** [comment]
@Tumite the nature of Tor is that it will route your traffic to available exit nodes anywhere in the world. It is not unexpected at all to see connections like that. Streisand runs a tor bridge, which is a node that is *not* publicly listed, and so only someone who knows its details can connect to it. However, that bridge node will pass you further on to different nodes, and thus the possible connections with servers in Russia. 

See https://www.torproject.org/about/overview.html.en for more details on how Tor works.  The illustrations towards the bottom are particularly helpful to understand Tor. Please remember though, that Tor isnt designed to provide perfect security, but rather privacy + anonymity. Any exit node could be recording all the traffic that is coming across it, but it also doesnt know where that traffic came from.

**Comment by broland07** [comment]
Now understand.
Thank you the info, @nickolasclarke .

**Comment by cpu** [comment]
I'm going to close this issue since the question has been addressed. Thanks everyone!
