### ISSUE TITLE
OpenVPN profiles

### ISSUE THREAD

**Issue by broland07** [jlund/streisand-discussions#101]
Hello guys!

I try to figure out but i don't find any information about OpenVPN profiles. (mandate-outer,only-clay,rigid-acoustic,tilt-worth,wine-leg)
What is the difference between these profiles?

**Comment by cpu** [comment]
Hi @Tumite,

The best way to think about these profiles is as separate user/password combinations (this is a simplification, but in practice they can be thought of similarly).

Two users can't use the same profile at the same time, so you need to give `mandata-outer` to one user, `only-clay` to another, etc.

Hope this helps,

**Comment by broland07** [comment]
Yep, thanks @cpu , now i understand.

**Comment by cpu** [comment]
Great! Happy to help.

I opened https://github.com/StreisandEffect/streisand/issues/1202 on the primary repo to keep a TODO for making this easier to understand. You aren't the first one who has had these questions :-)

**Comment by broland07** [comment]
Super, good idea! 👍
