### ISSUE TITLE
Documentation for OpenConnect GUI on Mac

### ISSUE THREAD

**Issue by GauthierPLM** [jlund/streisand-discussions#103]
Not all users are experienced with command line and it would be good to have a documentation describing how to configure OpenConnect GUI to work with Streisand. I am mainly thinking to people who don't have a special requirement (and therefore knowledge) to bypass censorship but still want to get free from it. On Mac, it is suggested to use the CLI but most users don't know how to use it, nor are ready to launch the VPN from it every times they need it. That's why I think it would be a good addition.

**Comment by cpu** [comment]
Hi @GauthierPLM,

Sounds like a good idea. Are you interested in contributing documentation for this?

**Comment by GauthierPLM** [comment]
Hello,

I am in to contribute, however, could you indicate me which file I need to edit to add the documentation?

**Comment by nickolasclarke** [comment]
@GauthierPLM for english, you would be adding to this file: https://github.com/StreisandEffect/streisand/blob/master/playbooks/roles/openconnect/templates/instructions.md.j2

There is a language file for french, if you happen to speak french as well. If not, one of us francophones on the project will pick it up once your PR is accepted.

**Comment by GauthierPLM** [comment]
As this is now available, I think the issue can be closed.
