### ISSUE TITLE
[Help Wanted] Cannot connect throught OpenVPN with stunnel (was: stunnel error: address already in use)

### ISSUE THREAD

**Issue by cnzhx** [jlund/streisand-discussions#104]
Hi there,

I just tried to install the streisand on google cloud platform. The OS chosen is Ubuntu 16.04. 

Firstly, Streisand failed when I tried to install remotely from an newly installed openSUSE Tumbleweed VM. It said it requires libcloud<=1.17.0 but obviously I had installed libcloud according to the instructions. Then, I directly installed Streisand inside the GCP instance with "LocalHost (advanced)" option. All seems working except the OpenVPN through Stunnel one (I am still trying other options).

I use SSLDroid on my phone with OpenVPN for Android. OpenVPN log shows it failed a lot of times. It still cannot connect now.

From the console of GCP, I tried to run `sudo stunnel`. It returns following messages:
```$ sudo stunnel
[ ] Clients allowed=500
[.] stunnel 5.30 on x86_64-pc-linux-gnu platform
[.] Compiled/running with OpenSSL 1.0.2g  1 Mar 2016
[.] Threading:PTHREAD Sockets:POLL,IPv6,SYSTEMD TLS:ENGINE,FIPS,OCSP,PSK,SNI Auth:LIBWRAP
[ ] errno: (*__errno_location ())
[.] Reading configuration from file /etc/stunnel/stunnel.conf
[.] UTF-8 byte order mark not detected
[.] FIPS mode disabled
[ ] Compression disabled
[ ] PRNG seeded successfully
[ ] Initializing service [stunnel]
[ ] Loading certificate from file: /etc/stunnel/stunnel.crt
[ ] Certificate loaded from file: /etc/stunnel/stunnel.crt
[ ] Loading private key from file: /etc/stunnel/stunnel.key
[ ] Private key loaded from file: /etc/stunnel/stunnel.key
[ ] Private key check succeeded
[ ] DH initialization
[ ] Using DH parameters from /etc/stunnel/stunnel.crt
[ ] 2048-bit DH parameters loaded
[ ] ECDH initialization
[ ] ECDH initialized with curve prime256v1
[ ] SSL options: 0x07004004 (+0x07004000, -0x00000000)
[.] Configuration successful
[ ] Listening file descriptor created (FD=7)
[!] bind: Address already in use (98)
[!] Error binding service [stunnel] to 0.0.0.0:993
[ ] Closing service [stunnel]
[ ] Service [stunnel] closed
```

Any suggestion is welcomed!

Thank you in advance!

**Comment by cnzhx** [comment]
Sorry that I had made a mistake. It should be `stunnel4` instead of `stunnel` running in the server. I checked with `systemctl status stunnel4` and it showed the service is running.

But I still cannot connect through this way. The OpenVPN client in my android phone connects and losts the connection right away. 

On the server, journalctl shows stunnel4 service keeps report `LOG3[25]: SSL_accept: Peer suddenly disconnected` when no client tries to connect. And it shows following messages when the phone tries to connect,
```
LOG3[5]: SSL_accept: Peer suddenly disconnected
LOG3[6]: SSL_read: Connection reset by peer (104)
LOG3[8]: s_connect: connect ::1:636: Connection refused (111)
LOG3[9]: SSL_accept: Peer suddenly disconnected
LOG3[8]: SSL_read: Connection reset by peer (104)
LOG3[7]: SSL_read: Connection reset by peer (104)
LOG3[12]: s_connect: connect ::1:636: Connection refused (111)
LOG3[11]: SSL_read: Connection reset by peer (104)
......
LOG3[21]: SSL_accept: Peer suddenly disconnected
LOG3[22]: SSL_accept: Peer suddenly disconnected
LOG3[18]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
```
Could anyone point me to the right direction for solving this problem?

**Comment by ghost** [comment]
I would kill stunnel and then restart it to make sure you're still getting the line:

[!] Error binding service [stunnel] to 0.0.0.0:993

That line is indicating port 993 is already in use. That is secure IMAP by default (really wish they didn't configure it this way as I can't use stunnel without port 443). Do you have an IMAP server running on that server?

**Comment by cnzhx** [comment]
Hi @jasonekratz , thank you for your reply and sorry for that I have misled you. I figured out the problem you said and made stunnel run smoothly. However, the function is still not right with the messages shown in the comment by myself. I should've created a new issue instead of just modify this one. I will do so after this reply to you.
