### ISSUE TITLE
OpenVPN Profiles... again

### ISSUE THREAD

**Issue by wicknet** [jlund/streisand-discussions#109]
@ CPU - I understand that OpenVPN profiles can't be generated post-provisioning (Issue #92).

However, for situations where Streisand is deployed and used within the US merely to bypass overly restrictive workplace environments or to access torrent sites, OpenVPN and TorBridge end up being the most heavily-used services.

Since folks spinning up Streisand instances also wind up helping family and friends get privacy online, wondering if it would be possible to change the default number of OpenVPN profiles generated from 5 to at least 10 or preferably 20 at the time of provisioning the server?  With just 5 profiles, it becomes inevitable that they get recycled heavily, with potentially adverse consequences (5 identical clients connecting from 5 different devices / locations).

Many Thanks for considering.

**Comment by cpu** [comment]
> wondering if it would be possible to change the default number of OpenVPN profiles generated from 5 to at least 10 or preferably 20 at the time of provisioning the server? 

@wicknet Yes, this is possible. When setting up the Streisand instance you need to answer "yes" when asked if you want to customize the services. The very first question in the customization is how many client profiles to generate.

Hope that helps,

**Comment by wicknet** [comment]
Great news. Definitely missed that during setup.

Thanks SO much!
