### ISSUE TITLE
Are providers like Vultr and Aruba getting blocked in China?

### ISSUE THREAD

**Issue by aanwark** [jlund/streisand-discussions#110]
So I have been using Vultr and Aruba for quite sometime. Last week my streisand VPS with Aruba got blocked by the GFW. I tried pinging the IP and it didn't respond at all. I tried to configure a new server with Vultr and it doesn't matter how many servers I spin, all of them seem to be blocked already. Also I noticed that most of Vultr VPS IPs are starting with 45.x.x.x. Anyone else having these problems? Like spinning up VPS and finding out that their IPs are already blocked?

**Comment by nickolasclarke** [comment]
Yes, I've had serious problems with Vultr Japan and with Aliyun. There are some solutions that I've found, but none are terribly reliable at the moment. I am interested to see what happens now the the party congress has officially ended.

**Comment by aanwark** [comment]
I was expecting this, I tried pinging the IPs from many other locations in China (using a tool available from Baidu) and had the same issue. Digital Ocean seems to be working for now, however can't say how long will it last.

**Comment by nickolasclarke** [comment]
@denoza have you seen any improvement after the end of the the meetings?

**Comment by aanwark** [comment]
Yes, I ran a vultr instance few days ago and it was pinging fine. For now, I am on Aruba and so far so good. How are things at your end?

**Comment by nickolasclarke** [comment]
I think we can close this out. Feel free to reopen if needed @denoza
