### ISSUE TITLE
ddwrt

### ISSUE THREAD

**Issue by cam-l** [jlund/streisand-discussions#112]
So I know this is not the place for advice on supporting router firmware. But i have been running an old version of streisand ovpn seamlessly for about 12months. Just tried to instance a new build on a new vultr server and it of course spins up beautifully.. everywhere except ddwrt. Updated the router so both server and client are running ovpn 2.45 but still no luck. Client logs are not helpful, but looks like it fails just before or during the handshake.

Anyone have any experience in ddwrt and know what important thing might have changed between old streisand and new streisand, or where to look at server logs to find out where the issue might be? Happy to give further details, but aware this use case is not supported so also don't want to waste anyone's time.

**Comment by alimakki** [comment]
Hi @cam-l,

I can't say much for DD-WRT but one of the significant changes in Streisand with regards to OpenVPN was that `tls-auth` was deprecated in favor of `tls-crypt`, which I suspect could be the cause.

Out of curiosity, have you tested only with ddwrt?

**Comment by cam-l** [comment]
Ok thanks. Will have a look at that tomorrow. Works fine on Ubuntu, win, android..

**Comment by cam-l** [comment]
Hi @alimakki 

Thanks very much for your help. It was indeed a case of `tls-auth` being deprecated. This is currently hard-coded into the ddwrt openvpn library startup routine. I can get Streisand temporarily up by killing the pid process then rewriting the conf file and starting the vpn again. 

ie:

```
#!/bin/sh

# gets around ddwrt hardcoded tls-auth, apply your settings in gui then run script from ssh session

# ps -w lists pid info, grep find running openvpn, cut cuts the pid off, xargs kills it
ps -w | grep [o]penvpn | cut -c 1-5 | xargs kill

# sed - i to replace line.. 26 is the line number of the auth issue.. hacky i know
sed -i '26s~.*~tls-crypt /tmp/openvpncl/ta\.key~' /tmp/openvpncl/openvpn.conf

# restart the openvpn service
openvpn --config /tmp/openvpncl/openvpn.conf --route-up /tmp/openvpncl/route-up.sh --route-pre-down /tmp/ --daemon
```

**Comment by alimakki** [comment]
@cam-l thanks for pointing out your solution, I'm sure it will be of great help to others who run into the same issue.

Cheers!
