### ISSUE TITLE
new server lets encrypt problem

### ISSUE THREAD

**Issue by covici** [jlund/streisand-discussions#114]
Hi.  So, I did a new server on a Ubuntu 16.04 platform.  It asked for the domain for lets encrypt purposes,  I entered the domain, but not the hostname of the server -- was I supposed to enter servername.domain instead?

How can I rerun to fix this problem and what do I change and where?

Thanks in advance for any suggestions.

**Comment by cpu** [comment]
Hi @covici,

>  I entered the domain, but not the hostname of the server -- was I supposed to enter servername.domain instead?

Can you explain a little bit more what you entered with some concrete examples? I'm not sure I understand 100%.

> How can I rerun to fix this problem and what do I change and where?

You can destroy the created server and recreate it. Streisand doesn't support re-running in place very well.

**Comment by covici** [comment]
OK, so when it asked for the domain I said covici.com which is,
indeed, my domain.  Should I have said <my server-name>.covici.com
instead?    I did a backup of the server before installing Streisand,
so I could start over, if necessary -- I thought I saw something which
said  something about replay or something like that.

On Sun, 29 Apr 2018 11:05:59 -0400,
Daniel McCarney wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> [2  <text/html; UTF-8 (quoted-printable)>]
> Hi @covici,
> 
>  I entered the domain, but not the hostname of the server -- was I supposed to enter servername.domain instead?
> 
> Can you explain a little bit more what you entered with some concrete examples? I'm not sure I understand 100%.
> 
>  How can I rerun to fix this problem and what do I change and where?
> 
> You can destroy the created server and recreate it. Streisand doesn't support re-running in place very well.
> 
> ―
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici wb2una
         covici@ccs.covici.com

**Comment by cpu** [comment]
Aha! Thanks for explaining. I understand now.

> OK, so when it asked for the domain I said covici.com which is, indeed, my domain.  Should I have said <my server-name>.covici.com instead? 

That's correct. You need to enter the fully qualified domain name. The whole thing you would enter in a web browser to visit the domain.

>  I thought I saw something which said  something about replay or something like that.

This is part of the Ansible system Streisand is built on. It won't work well in this case, the Let's Encrypt domain name is populated by a setup phase before the main playbooks are run.

**Comment by covici** [comment]
OK, I will restore to berfore streisand and try again.  You might want
to change the prompt to say enter the fully qualified domain name of
the server or some such.

Thanks.

On Sun, 29 Apr 2018 11:59:15 -0400,
Daniel McCarney wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> [2  <text/html; UTF-8 (quoted-printable)>]
> Aha! Thanks for explaining. I understand now.
> 
>  OK, so when it asked for the domain I said covici.com which is, indeed, my domain. Should I have said .covici.com instead?
> 
> That's correct. You need to enter the fully qualified domain name. The whole thing you would enter in a web browser to visit the domain.
> 
>  I thought I saw something which said something about replay or something like that.
> 
> This is part of the Ansible system Streisand is built on. It won't work well in this case, the Let's Encrypt domain name is populated by a setup phase before the main playbooks are run.
> 
> ―
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici wb2una
         covici@ccs.covici.com

**Comment by cpu** [comment]
> You might want to change the prompt to say enter the fully qualified domain name of the server or some such.

Good idea. I submitted a pull request to change the prompt wording in https://github.com/StreisandEffect/streisand/pull/1313 

I'm going to close this issue since we've addressed the original question. Thanks!
