### ISSUE TITLE
Cannot install Steisand

### ISSUE THREAD

**Issue by xregs** [jlund/streisand-discussions#120]
Hi everyone.
I'm trying to install Streisand to DO server. But got error on this step:

> TASK [gpg : Start the GPG agent] *****************************************************************************************************************************
> fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["gpg-agent", "--homedir", "/root/.gnupg", "--use-standard-socket", "--daemon"], "delta": "0:00:00.361822", "end": "2018-05-06 17:52:45.260309", "msg": "non-zero return code", "rc": 2, "start": "2018-05-06 17:52:44.898487", "stderr": "gpg-agent[17546]: WARNING: \"--use-standard-socket\" is an obsolete option - it has no effect\ngpg-agent: a gpg-agent is already running - not starting a new one", "stderr_lines": ["gpg-agent[17546]: WARNING: \"--use-standard-socket\" is an obsolete option - it has no effect", "gpg-agent: a gpg-agent is already running - not starting a new one"], "stdout": "", "stdout_lines": []}

How can i fix this?

**Comment by ham-grey** [comment]
Good day, did you run the script once or repeatedly after an unsuccessful installation attempt?
I performed the installation on the localhost and got a similar error if I ran the script again after an unsuccessful installation attempt, I was helped by the reboot and the launch of the script after the command sudo su.
Although I'm not sure that I solved the problem correctly, the installation after that was completed, with a warning about the error in the process, but nevertheless, overall the installation was successful.
Perhaps,reboot or manually shutting down processes started by the script and then restarting the installation can help.

**Comment by cpu** [comment]
> gpg-agent: a gpg-agent is already running - not starting a new one

I suspect this was a bug introduced for existing/localhost servers with a running `gpg-agent` in https://github.com/StreisandEffect/streisand/commit/36a0e3650516df96e68a579b6c13a7dcc11c8f48.

One workaround until the bug is fixed is to explicitly kill the running `gpg-agent` with `sudo killall gpg-agent`. 

I'll try to address this properly in the coming days.

**Comment by xregs** [comment]
Thank you all for your answers. I still noob in this matter and solved the problem by resetting a dropplet. Then everything was set up again according to the manual without any experiments. Everything worked out.
