### ISSUE TITLE
Okay to run this inside my home LAN ?

### ISSUE THREAD

**Issue by ghost** [jlund/streisand-discussions#126]
Hello,

I like the idea of this software and I want to play around with it from my home network. I have a couple of questions:

1. Can this handle dyn dns entries or otherwise handle a network with a dynamic IP address? 

2. Is this even something that can be used wisely from a home network or will it cause more issues than it's worth?

Thank you!

**Comment by nopdotcom** [comment]
Sorry for the slow response on a simple question. I'd recommend playing with this on a supported cloud provider first. Running it at home can be a lot more complicated.

The Streisand server does not cope with its IP address changing at all--we all wish it did. :-(
