### ISSUE TITLE
Nextcloud alongside Streisand

### ISSUE THREAD

**Issue by aanwark** [jlund/streisand-discussions#128]
I have been trying to setup Nextcloud alongside Streisand on my instance. In this regard, I run a fresh vps, install streisand instance first and then Nextcloud using the [instructions](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-nextcloud-on-ubuntu-16-04). I assign a domain name to Nextcloud instance and change its default ports by using the instructions [here](https://github.com/nextcloud/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy) (since ports `80` and `443` are acquired by Streisand). The problem is understanding the use of Streisand Nginx as the reverse proxy for the Nextcloud front end, I know that Nextcloud runs an apache server for providing the front end UI, however I couldn't access it through `https` at a custom port. Even after following this [process](https://github.com/nextcloud/nextcloud-snap/wiki/Putting-the-snap-behind-a-reverse-proxy). If anyone has done that before, then his/her help will be highly appreciated.

**Comment by nopdotcom** [comment]
See #130; the live nginx is configured at `/etc/nginx/sites-enabled/streisand`. Could you re-open if you run into specific issues past that?

If someone were to write a "how to use a Streisand Nginx as a reverse proxy" document, that could be helpful.
