### ISSUE TITLE
how to change the public ip on a droplet Digital Ocean

### ISSUE THREAD

**Issue by rdbox** [jlund/streisand-discussions#129]
I need help, how do I use my public ip in my Streisand???

 ### Additional Details:
##### *Operating System of client:*  ssh  terminal  

I have a number of questions:

1. I somehow do not have ansible program. during the installation it was, but now I have checked the error of such a program is not found.  Is this how it should be?
 
2. now I want to ask what to do with vps Digital Ocean. I installed streisand, then decided to make a snapshot of the finished droplet. And today I decided to restore the snapshot but I had a problem ip the address was kept old and the new ip should always be written manually.
How can this process be changed?

**can be there is a way at loading of a droplet to substitute a new ip address or somehow to make automatic replacement of old ip on new IP?**

**Comment by nopdotcom** [comment]
You should still have Ansible on the machine you installed Streisand from. It may be in a `virtualenv`; if you used `./util/venv-dependencies.sh ~/streisand-deps` to set up, you need to `source ~/streisand-deps/bin/activate` to get it back in your terminal's environment.

There's no good way to change the IP on an existing Streisand installation. :-( It's just embedded too many places. It's a long-standing requirement, and we haven't made much progress on it recently. We could always use help. PRs welcome.

**Comment by rdbox** [comment]
unfortunately I do not have this program ansible

```
root@streisand-sgr:~/streisand# ansible
The program 'ansible' is currently not installed. You can install it by typing:
apt install ansible
root@streisand-sgr:~/streisand#
```
