### ISSUE TITLE
Generic webservices on port 80/443 also?

### ISSUE THREAD

**Issue by ivomarino** [jlund/streisand-discussions#130]
Hi there, I was wondering if it's possible to run also generic hosted webservices like Apache2 or HAProxy on 80/443 alongside Streisand. I would like to use the Streisand server also for generic webhosting, is that possible some way? maybe putting hands on:

```
tcp 0 0 <public_ip>:443      0.0.0.0:*    LISTEN  0   2236339     27950/sslh
```

thanks for feedback.

**Comment by nopdotcom** [comment]
It may not be the best idea to reuse a Streisand server this way. That being said:

sslh forwards HTTPS connections to nginx. You can modify `/etc/nginx/sites-enabled/streisand`. You may be able to run other services by configuring nginx as a reverse proxy.
