### ISSUE TITLE
L2TP/IPSEC vpn option

### ISSUE THREAD

**Issue by stepanovdg** [jlund/streisand-discussions#131]
To have ability to connect to VPN without installing any non-native clients and rather more secure then pptp. OVPN is working rather slow in case of router-client. A lot of routers has hardware IPSEC implementation.

**Comment by cpu** [comment]
Hi @stepanovdg,

Streisand previously had a L2TP/IPSEC implementation but it was based on insecure legacy settings & was too much of a maintenance burden. See: https://github.com/StreisandEffect/streisand/issues/1222

If you are looking for an IPSEC based solution I recommend you try [Algo](https://github.com/trailofbits/algo).

**Comment by stepanovdg** [comment]
Thank you.
