### ISSUE TITLE
Run in Windows using Bash?

### ISSUE THREAD

**Issue by Deiteq** [jlund/streisand-discussions#133]
Hi!
Great project you have here.

Just curious if this can be run using Windows Ubuntu Bash install?
I recently learnt about it and have added a quick description on how to install it on our PlexGuide Wiki's which you can find here:-
https://plexguide.com/wikis/ssh-server-access/#8-windows-users

Thought you may want to try it if you haven't already and if it works then it gives your Windows user a chance to try your stuff! ;-)

Anyway, I'm looking for ways to make peoples server more secure and this project intrigues me....will bookmark it to test it out someday soon!

**Comment by alimakki** [comment]
Hi @Deiteq 

Although not "officially" supported, it does work quite well (using Ubuntu bash) in my experience.

**Comment by Deiteq** [comment]
Perfect!
Will try it that way then...Thanks!

**Comment by alimakki** [comment]
Just an FYI, when getting started there's a handy script in the util directory named 'ubuntu-dependencies.sh` that greatly simplifies getting everything you need for Streisand to execute successfully.
