### ISSUE TITLE
Deactivate gateway

### ISSUE THREAD

**Issue by octupole** [jlund/streisand-discussions#137]
Hello everybody!
How does one deactivate the streisand gateway? What kind of webserver is the gateway using? No trace of the streisand gateway on the apache2 config files. 
Thank you beforehand!
Mas

**Comment by octupole** [comment]
I answer my own questions! The webserver is nginx. And it is pretty easy to stop it or reconfigure.

**Comment by alimakki** [comment]
Closing since OP has resolved the issue.
