### ISSUE TITLE
Why Google DNS ?

### ISSUE THREAD

**Issue by aeroweb340** [jlund/streisand-discussions#140]
Hi,

Is there a possibility to avoid using Google DNS ?

Why not Cloudflare or Quad9  by default ?

Many thanks,

**Comment by alimakki** [comment]
Hi @aeroweb340,

There is nothing stopping you from changing the DNS server for your installation.

Prior to running `./streisand`, just edit the `vars.yml` in the [global_vars](https://github.com/StreisandEffect/streisand/blob/b2ff836124e9339dbb708b3364fc3e6484104e38/global_vars/vars.yml#L2) file with the servers you wish to use.

**Comment by aeroweb340** [comment]
Ok thanks. But Streisand is already installed on my server. How can I modify this without reinstalling the all thing.

**Comment by aeroweb340** [comment]
I edited the ocserv.conf changed the DNS and did reboot the server. Still the same Google DNS... Any idea?

**Comment by alimakki** [comment]
@aeroweb340 You may want to look at `/etc/resolv.conf` as well, in addition to configurations for dnsmasq under `/etc/dnsmasq.conf`

**Comment by aeroweb340** [comment]
dnsmasq.conf all good thanks !
