### ISSUE TITLE
compress lz4 openvpn Voracle attack

### ISSUE THREAD

**Issue by aeroweb340** [jlund/streisand-discussions#153]
Hi,

Compression seems to be not recommended these days (Voracle attack). In fact it is disabled by default on the last openvpn version on iOS.  I had to manually set compression to FULL to be able to browse the internet again...

I was wondering if the team plan to remove the compression or if I can edit the server conf... ?

Thanks a lot

[https://protonvpn.com/blog/voracle-attack/](url)

**Comment by alimakki** [comment]
@aeroweb340, compression for OpenVPN has been disabled as of PR [#1427](https://github.com/StreisandEffect/streisand/commit/353bb09a552b455ade512271f764968bb01ea6c3).

You can edit your OpenVPN server configurations to disable them by modifying `server.conf` and `server-udp.conf` with the following change:

replace 
```
compress lz4
```

with
```
compress
```

to disable compression.

**Comment by aeroweb340** [comment]
Perfect thanks !
