### ISSUE TITLE
[Need help]How to quick change domain

### ISSUE THREAD

**Issue by CaiJingLong** [jlund/streisand-discussions#173]
Thank you for this great project.
After deployment, I need to modify the original domain name for some reasons, but the HTTPS certificate needs to be reapplied and deployed to take effect.
Is there a way to implement it quickly without requiring a full script run?

**Comment by cpu** [comment]
Hi @CaiJingLong - there is no easy way to change the domain name after deploying. You'll have to destroy the Streisand instance and create another.

**Comment by CaiJingLong** [comment]
I see SSL that seem to be using `acme.sh`.  Can I apply for certificates by rerunning `acme.sh` and configuring `nginx` to do this?
Or can I just rerun the script in its entirety?
