### ISSUE TITLE
adding new service provider

### ISSUE THREAD

**Issue by computer777** [jlund/streisand-discussions#196]
Hey there Streisand devs. I picked up a prebuilt Debian OS VPS pack in which the service is provided by World Servers. So I chose option 8 for the initial ./Streisand option.

I'm just now thinking it's not designed for a Debian install.

But, anyway, when it was time to do so I input the IP address of the server.

But, it was unable to process the request due to having a password.

Any way to accommodate this (ssh password required).
For the non intereractive install it can point to --user , but what about password?

Hoping this is clear

**Comment by nickolasclarke** [comment]
@computer777 quickly responding on mobile, so I cant go into full detail here but: 

1. Streisand is designed for Ubuntu 16.04 at the moment, Debian is not supported. 
2.  Your host must be accessible via a ssh key-pair. 

further instructions on how to do an install against an unsupported service provider can be found here: 

https://github.com/StreisandEffect/streisand/blob/master/Advanced%20installation.md
