### ISSUE TITLE
IPSec IKEv2

### ISSUE THREAD

**Issue by cpu** [jlund/streisand-discussions#21]
Suggested by @chenhouwu in https://github.com/jlund/streisand/issues/110
> Would like to have support of IPSec without l2tp.
> l2tp is blocked often by GFW,
> I hear that IKEv2 is never blocked.

There is some substantial follow-up discussion from @jlund and others in https://github.com/jlund/streisand/issues/110 that should be referenced by anyone wishing to restart this discussion here.

**Comment by cpu** [comment]
Also came up in https://github.com/jlund/streisand/issues/85

**Comment by lgg** [comment]
@cpu what we need to do to add ikev2 support? Any ideas how to release this?

**Comment by alimakki** [comment]
@lgg, I'm working on a PR to do this.

**Comment by nopdotcom** [comment]
Rolling it out isn't really the problem. We've got infrastructure to build
client certs, and the server sitting there. Mostly what it will take is a
pointer to a good, somewhat-commented configuration file. Uh, plus a lot of
instructions.

I can write the instructions, although it takes time.

**Comment by lgg** [comment]
@alimakki is there anything i could help you with?

@nopdotcom i think we can take a lot of information from https://github.com/trailofbits/algo/ and [StrongSwan Wiki](https://wiki.strongswan.org/projects/strongswan/wiki/)

**Comment by alimakki** [comment]
@lgg for now no, although I do appreciate the offer. I'll try to get a skeleton implementation by the end of this upcoming weekend, perhaps then some testing and feedback would be useful.

**Comment by no-usernames-left** [comment]
**+1** to this idea. [This link](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md) might help whoever is implementing IKEv2 for Streisand (which I think is a fabulous idea, even just for the mobility support).

**Comment by faeton** [comment]
Has there been any progress towards IKEv2 implementation? It is pretty important and seems like ez to integrate using libre/strongswan

**Comment by cpu** [comment]
@faeton This should be closed, there's no work going on in this direction. Streisand decided to remove all of the existing IPSec based VPN code. I recommend you look into [Algo VPN](https://github.com/trailofbits/algo) if you are interested in IPSec/IKEv2.
