### ISSUE TITLE
shadowsocks traffic detection

### ISSUE THREAD

**Issue by cpu** [jlund/streisand-discussions#25]
@OneHappyForever asks in https://github.com/jlund/streisand/issues/501:
> Hi,
>
> Just wanted to know what you guys think of the shadowsocks traffic detection apps made available by shadowsocks and shadowsocksR developers. Do you think they point to possible weak points and areas of imporovement?
>
> Here are the links:
> https://github.com/madeye/sssniff
> https://github.com/breakwa11/shadowsocks-rss/issues/868

**Comment by cpu** [comment]
@OneHappyForever My thoughts on this issue match [@riobard's comment](https://github.com/shadowsocks/shadowsocks-org/issues/73#issuecomment-317608838).

**Comment by wfjsw** [comment]
Just ignore that. They don't make any sense if you look at that carefully.
There is deep argument between SS & R-variant. It is thought that R-variant's author opened 868 just to cause panic and to promote the variant.

**Comment by cpu** [comment]
It seems like there aren't any follow-up questions on this topic so I'm going to close this discussion issue. Thanks!
