### ISSUE TITLE
Which dns service is used?

### ISSUE THREAD

**Issue by bobolea** [jlund/streisand-discussions#26]
Hi,

This might be a silly question but what dns service is used for Streisand when using Ipsec?

Thanks

**Comment by alimakki** [comment]
Google DNS

**Comment by bobolea** [comment]
Ok thanks, is this Google DNS a good choice when it comes to privacy and if not can the choice of dns be changed somehow?

**Comment by alimakki** [comment]
@bobolea, you can change the DNS servers by editing the [global_vars/vars.yml](https://github.com/jlund/streisand/blob/master/global_vars/vars.yml) file, the setting is `upstream_dns_servers`.

I find Google DNS to be very reliable, however when it comes to privacy I suggest you visit their [FAQ](https://developers.google.com/speed/public-dns/privacy), see if that helps answer questions you might have.

**Comment by cpu** [comment]
Since the original question has been answered I'm going to close this thread. Thanks for asking!
