### ISSUE TITLE
AWS blocks the use of its VPS as VPNs from China

### ISSUE THREAD

**Issue by aanwark** [jlund/streisand-discussions#35]
I thought this news might be relevant here.

https://www.reuters.com/article/us-amazon-china-vpn-idUSKBN1AI0CM

Now China users are one provider short.

**Comment by nickolasclarke** [comment]
I think this only matters if you are using an AWS china account. If you have an AWS account outside of china, this should not effect you. Still an unfortunate, if entirely predictable turn of events.

**Comment by nickolasclarke** [comment]
Cleaning shop a bit, closing!
