### ISSUE TITLE
Shadowsocks method chacha20-ietf-poly1305 not supported

### ISSUE THREAD

**Issue by dmmeow** [jlund/streisand-discussions#40]
I can't make any shadowsocks client on Ubuntu 16.04 run connect to streisand with method chacha20-ietf-poly1305. I always get this
`chacha20-ietf-poly1305`
I updated my shadowsocks-libev to 3.0.8, which should have solved this problem as this method is supported since version 3, but to no avail.
So, my question is can I change the method on my streisand-server post- or pre-installation?

**Comment by aanwark** [comment]
Do you have this problem with your client? Please install [libsodium](https://github.com/jedisct1/libsodium) on your Ubuntu client.

**Comment by cpu** [comment]
> I always get this
> chacha20-ietf-poly1305

Did you mean to share a more complete error trace? It seems like perhaps it got cut off?

**Comment by cpu** [comment]
Closing for lack of info.

**Comment by FrankFang** [comment]
sudo apt-get install libsodium-dev
