### ISSUE TITLE
Translation "How-to"

### ISSUE THREAD

**Issue by thiras** [jlund/streisand-discussions#43]
Hello,

Thank you for this amazing project. It worked like a charm. Especially if you live country has terrible freedom of speech standards.

My suggest will be to create a how-to about translating "generated-docs" and readme file into foreign languages. I personally would like to translate into my language but couldn't find proper "how to translate" documents.

Doesn't matter for me the skill level of document but "The simpler how-to the more translation" in my opinion.

**Comment by cpu** [comment]
Hi @thiras,

Thanks for the kind words. Glad to hear Streisand was helpful to you! :fist_raised: 

@alimakki What do you think about this request? Do you think you could write a quick `.md` for the `docs/` folder that has the basics of what needs to be translated/tips?

**Comment by alimakki** [comment]
I think that's something I can do.

**Comment by alimakki** [comment]
@thiras, I submitted a [PR](https://github.com/jlund/streisand/pull/954) for a how-to guide on translation.

Let me know if this helps, what works, what doesn't.

Feedback is always appreciated!

**Comment by cpu** [comment]
The PR @alimakki wrote up was merged to master. [You can read the guide here](https://github.com/jlund/streisand/blob/master/documentation/localization_howto.md).

Thanks for the idea @thiras ! If you find the howto doesn't explain something you're confused about please let us know or submit an update :-)
