### ISSUE TITLE
"Bad encapsulated packet length from peer"

### ISSUE THREAD

**Issue by describe19** [jlund/streisand-discussions#44]
Have installed streisand on a DO server with only OpenVPN and stunnel, when i try and connect with stunnel in OSX i get:

Bad encapsulated packet length from peer (10784), which must be > 0 and <= 1575 -- please ensure that --tun-mtu or --link-mtu is equal on both peers -- this condition could also indicate a possible active attack on the TCP link -- [Attempting restart...]

from tunnelblick.
Any ideas? Should i just try and set up the server again?

**Comment by cpu** [comment]
Sounds like a bug! Thanks for opening https://github.com/jlund/streisand/issues/962 for that. I'm going to close this issue to centralize discussion on https://github.com/jlund/streisand/issues/962.
