### ISSUE TITLE
Update configuration - run installation again

### ISSUE THREAD

**Issue by tobru** [jlund/streisand-discussions#45]
I'm somehow not able to find an answer to my question: How can I re-run the Streisand playbooks on an already configured Streisand VPN server to update the configuration to the latest version without loosing the already available configuration (f.e. client certificates of OpenVPN, etc.)?

**Comment by cpu** [comment]
Hi @tobru - this isn't supported by Streisand presently. https://github.com/jlund/streisand-discussions/issues/17 is the ticket I think of for this feature request. https://github.com/jlund/streisand-discussions/issues/30 may also be related.

It's something the maintainers have discussed moving towards but its a ways off and there isn't a concrete proposal for how it will be managed yet.

For now the recommendation is to provision a brand new Streisand instance and migrate to it without preserving data from the original instance.

**Comment by tobru** [comment]
Thanks @cpu for the information... Let's see how it progresses, would be great if this is possible one day.

**Comment by cpu** [comment]
n/p @tobru - thanks for inquiring. I'm going to close this discussion issue for now since I think following the linked issues will be the best way to keep track of progress. Thanks again,
