### ISSUE TITLE
Do the recently-disclosed dnsmasq vulns need to be addressed?

### ISSUE THREAD

**Issue by witte-de-with** [jlund/streisand-discussions#47]
Right now it looks like streisand boxes are using a vulnerable version of dnsmasq. Version 2.78 is the latest and includes a lot of security fixes. I see 2.75 on my streisand instance. Would there be a way to address this soon?

**Comment by cpu** [comment]
@i-s-o-g-r-a-m I'm surprised the package hasn't updated automatically by way of [unattended-upgrades](https://github.com/StreisandEffect/streisand/blob/c9ebea9b2cff23d62ac74b4381eb30655d0838dd/playbooks/roles/common/tasks/main.yml#L55:L64) and the [templated configuration](https://github.com/StreisandEffect/streisand/blob/c9ebea9b2cff23d62ac74b4381eb30655d0838dd/playbooks/roles/common/templates/50unattended-upgrades.j2) Streisand writes.

When you log in to the Streisand instance does it say there are security updates available?

**Comment by cpu** [comment]
@i-s-o-g-r-a-m Can you share the output of `dpkg -l dnsmasq | less`? @alimakki just checked one of his old (quite old! 14.04 old!) Streisand instances and it had applied the correct version automatically.

Based on [USN-3430-1](https://usn.ubuntu.com/usn/usn-3430-1/) a 14.04 instance should have `dnsmasq` version ` 2.68-1ubuntu0.2` and that's what @alimakki found (Thanks for checking!!!).

On your 16.04 system you should find `dnsmasq` version `2.75-1ubuntu0.16.04.3`.

I suspect 2.78 is the newest version available from the upstream project but it's typical on a Ubuntu LTS system for the package to remain at an older version that the Ubuntu folks backport security fixes to.

**Comment by cpu** [comment]
@nickolasclarke also checked a running 16.04 instance provisioned a few months ago and it had installed `2.75-1ubuntu0.16.04.3`

I feel confident we don't need to do anything explicit to address this vulnerability. Thanks for checking!

**Comment by nopdotcom** [comment]
Given how high profile this vuln was, it might be worth noting somewhere that Debian/Ubuntu usually backport fixes rather than upgrading to a new release.

But of course this issue in archives *is* noting that.

**Comment by witte-de-with** [comment]
Thanks @cpu and @nopdotcom for the consideration of this issue.

@cpu I can confirm `2.75` is the dnsmasq version I've got. I also agree 2.78 is the newest one where the vulnerabilities have been addressed.

@nopdotcom thanks for the point about fixes being backported; that was new information for me.

Glad to hear the maintainers don't feel any action is necessary right now, seems reasonable to me, and again I appreciate the consideration 👍

**Comment by cpu** [comment]
> @cpu I can confirm 2.75 is the dnsmasq version I've got. I also agree 2.78 is the newest one where the vulnerabilities have been addressed.

Great! Just to be 1000% crystal clear it's important to check that you have `2.75-1ubuntu0.16.04.3` exactly. `2.75` is ambiguous and could refer to the unpatched 2.75, not the specifically Ubuntu maintained version of 2.75 (which itself is at version `0.16.04.3`) that has the security fixes backported from `2.78` - Whew that's a mouthful!

I'm going to close this issue - Thanks for inquiring!

**Comment by witte-de-with** [comment]
@cpu ah, I see -- thanks for the clarification (and apologies for my slowness there). Yes, I've got `2.75-1ubuntu0.16.04.3`, so I think we're good. Thanks again!
