### ISSUE TITLE
Streisand Share Network

### ISSUE THREAD

**Issue by studerw** [jlund/streisand-discussions#48]
Finally just got this setup and using just the OpenVPN config so far.  I'm using a MSDN Azure cloud tied to an identity. 

Upon first connection, noticed that both Amazon and GMail didn't 'trust' me and required 2FA.
There goes my anonymity - the analytic networks are too advanced to hope this doesn't get passed on to other collectors. And I'm sure it's worse in places like China, Iran, etc. 

What's something we can do to create a peer-to-peer / share network of Streisand servers with minimal setup? We need some sort of trust-ring to avoid signing into the same VPN server, possibly via a proxy from our static server.

Or is this what TOR is supposed to accomplish? I'm not yet familiar with that, and will take a look.

**Comment by nopdotcom** [comment]
Notionally, 2FA happens after identification. Identification -> Authentication -> Authorization.

I think what you want is weaker than Tor, if you can trust the adversary can't listen in on the core. But go try Tor first.

**Comment by cpu** [comment]
Hi @studerw,

Thanks for inquiring/starting a discussion.

> Or is this what TOR is supposed to accomplish? I'm not yet familiar with that, and will take a look.

This is exactly what Tor is meant to accomplish. If you're interested in anonmity I strongly encourage you to look into using the Tor relay portion of your Streisand server & the Tor browser bundle. 

Tor is the only component of Streisand meant to deliver anonymity. The other VPN services (OpenVPN included) are **not** designed for anonymity and should not be relied upon for such.

Developing alternatives to Tor is well outside of what we have the resources to accomplish within the Streisand project.
