### ISSUE TITLE
Vagrant usage fails, is lacking documentation on key organization

### ISSUE THREAD

**Issue by exratione** [jlund/streisand-discussions#50]
Host system: Ubuntu 14.04, Ansible 2.4.0.0.

Jumping in fresh to look at Streisand, my expectation was that I could just launch the streisand-host Vagrant guest and start poking around. Sadly, `vagrant up streisand-host` just fails outright on the absence of a key.

```
PLAY [Prepare the vagrant VM for Ansible] **************************************

TASK [Gathering Facts] *********************************************************
ok: [streisand-host]

TASK [validation : Stat the Streisand SSH private key] *************************
ok: [streisand-host]

TASK [validation : Fail if the Streisand SSH private key file doesn't exist] ***
fatal: [streisand-host]: FAILED! => {"changed": false, "failed": true, "msg": "The Streisand SSH private key \"~/.ssh/id_rsa\" does not exist."}
```

So for the purposes of just getting it to work, I could:

```
mkdir ssh-keys
ssh-keygen
```

to put an `id_rsa` into a directory in the project, then map it in the `Vagrantfile`:

```
    streisand.vm.synced_folder "ssh-keys", "/root/.ssh"
```
This appears to get the job done, as would the dangerous choice of syncing my `~/.ssh`:

```
    streisand.vm.synced_folder File.expandPath("~/.ssh"), "/root/.ssh"
```

None of this is mentioned in the Streisand testing docs, however ( https://github.com/StreisandEffect/streisand/blob/master/documentation/testing.md ) which give the impression that all you have to do is fire up Vagrant and off you go.

How are the developers working with this? What is the preferred fix here?

**Comment by cpu** [comment]
Hi @exratione 

> None of this is mentioned in the Streisand testing docs, however ( https://github.com/StreisandEffect/streisand/blob/master/documentation/testing.md ) which give the impression that all you have to do is fire up Vagrant and off you go.

The Vagrant environment hasn't been updated to take into account SSH key customization. It's a new feature in master and I haven't had time to make it work with the Vagrant env yet. PRs welcome!

The documentation should be updated - it's not present there because at the time of writing all of Streisand assumed `~/.ssh/id_rsa` existed and so it wasn't a special requirement needing to be discussed in the testing doc. Since that's changed we should fix it until the Vagrant env supports alternative key locations.

> How are the developers working with this? What is the preferred fix here?

I generate a throw-away SSH key in `~/.ssh/id_rsa` for Vagrant.

**Comment by exratione** [comment]
Sounds like a documentation change is the short-term patch then.

As a less short-term patch, since Windows isn't supported, one could generate a throwaway key in the Vagrantfile if it doesn't already exist - a few lines of Ruby code to call down to ssh-keygen.

More generally, one could use something like https://github.com/bensie/sshkey to generate a throwaway keyfile as a part of the Vagrant file if it doesn't exist, at the cost of adding a bundle install to the requirements.

Or there is probably a Python module since you are primarily pip-based for dependencies, but I'm less familiar with that side of the fence.

**Comment by cpu** [comment]
> Sounds like a documentation change is the short-term patch then.

:+1: - I will add a note to the docs page.

> As a less short-term patch, since Windows isn't supported, one could generate a throwaway key in the Vagrantfile if it doesn't already exist - a few lines of Ruby code to call down to ssh-keygen.

@exratione I'd be happy to review a PR improving the Vagrantfile SSH. I'm going to be out of town this week and won't have a chance to make any improvements myself in the short term.

I'm flexible about adding dependencies to the Vagrantfile. It's not intended to be used by end-users at this point and I think of it exclusively as a development aid.

**Comment by exratione** [comment]
PR created; since the key isn't actually needed on the host, creating it in the `vagrant.yml` Ansible playbook seems the easiest way forward.

https://github.com/StreisandEffect/streisand/pull/1009

**Comment by exratione** [comment]
Closing as https://github.com/StreisandEffect/streisand/pull/1009 is merged.
