### ISSUE TITLE
streisand on Scaleway

### ISSUE THREAD

**Issue by quite** [jlund/streisand-discussions#51]
Trying to turn a Scaleway VC1S (x86) with Ubuntu Xenial 16.04 into a Streisand impersonator.

The Apparmor issue that @sundmoon mentioned in StreisandEffect/streisand#418 is solved by going into the server settings and changing the Bootscript under Advanced. I'm using the currently present `x86_64 4.10.8 apparmor #1` boot script.

Further into the Ansible playbook there was an error related to Wireguard, also something kernel related I think. I decided to restart the installation and disable Wireguard. This got the installation through completely, but I am yet to have verified the function of any of the services.

**Comment by cpu** [comment]
> Further into the Ansible playbook there was an error related to Wireguard, also something kernel related I think. I decided to restart the installation and disable Wireguard. This got the installation through completely, but I am yet to have verified the function of any of the services.

Wireguard depends on a kernel module - Scaleway's kernels are non-standard.

I don't recommend Scaleway as a provider for Streisand. We don't support it presently and given the number of divergences this host has compared to more standard choices I don't suspect this will change anytime soon.

Thanks for documenting the workaround for Apparmour!
