### ISSUE TITLE
OpenConnect and DNSMasq

### ISSUE THREAD

**Issue by sergiopatino** [jlund/streisand-discussions#60]
Any reason why dnsmasq is not used in the openconnect configuration?

**Comment by cpu** [comment]
@sergiopatino None I'm personally aware of. Are you seeing DNS leak directly to your local recursive resolver when you have OpenConnect connected? Can you elaborate on your device and configuration?

**Comment by cpu** [comment]
Closing this from inactivity. Please feel free to comment if you want to reopen.
