### ISSUE TITLE
Couldn't find 5 VPN client profiles

### ISSUE THREAD

**Issue by woofscary** [jlund/streisand-discussions#62]
Terribly sorry for the dumb question, but having seen "vpn_clients: 5" I assumed there should be 5 sets of logins/passwords/keys for 5 devices; however I can see only one set in "Connection Instructions" section. Where are 4 others?

**Comment by cpu** [comment]
@woofscary Which VPN service were you checking the instructions for? There are a few that don't have multiple client profiles yet (WireGuard for example). 

No need to apologize, we should definitely document the cases where there is outstanding work to accommodate multiple clients.

**Comment by woofscary** [comment]
Specifically I checked L2TP/IPSec service. I have connected successfully using cell phone or tablet with the same credentials.  Then I have tried to connect phone and tablet simultaneously; the latter refused to connect with the same login/password as the phone. So I assumed there should be different credentials for every device, but couldn't find other credentials than in "index.html".

**Comment by cpu** [comment]
@woofscary Hmmm! That does sound like a bug or something strange.

If you have a `streisand-diagnostics.md` file in your Streisand directory can you please share it here?

**Comment by woofscary** [comment]
### Ansible Information

* Ansible version: 2.4.0.0
* Ansible system: Linux
* Host OS: Ubuntu
* Host OS version:  16.04
* Python interpreter: python
* Python version: 2.7.12

### Streisand Information

* Streisand Git revision: c58d33776cf19570486858d636aad1d8c1c09d2f
* Streisand Git clone has untracked changes: 
* Genesis role: genesis-linode

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* L2TP enabled: True
* Configured number of VPN clients: 5

**Comment by cpu** [comment]
@woofscary Apologies, I lost track of this ticket. 

I was mistaken: Presently the L2TP/IPSec role is using PSK authentication, not certificate based authentication. That's why there aren't alternative client profiles created yet. @alimakki is [working on updating the role for IKEv2 and cert auth](https://github.com/StreisandEffect/discussions/issues/21#issuecomment-341542617).

I'm going to close this issue for now - it's expected behaviour that there are not multiple client profiles for L2TP.
