### ISSUE TITLE
Building a wrapper app around OpenConnect CLI macos: Security Implications?

### ISSUE THREAD

**Issue by peterpme** [jlund/streisand-discussions#65]
Hey,

I'm on MacOS and I've been having trouble finding a *good* openconnect client (or any client for that matter).

I've been running the command line version for now which is fine, but I was also thinking about creating a simple app that lets you type in a password & choose your key location and will then execute the command behind the scenes.

I feel like this _seems_ easy enough that a solution should exist. Maybe I'm googling the wrong words, or maybe its waaay harder than I think it is!

Are there any implications to this?
Is there an openconnect client that's just slipped through the cracks?

Thanks!

**Comment by cpu** [comment]
@alimakki Do you know what the client situation is like on OSX for OpenConnect?

**Comment by alimakki** [comment]
There is an OpenConnect GUI [project](https://github.com/openconnect/openconnect-gui), though I haven't had much success with it the last time I used it, continually crashed when pushing the connect button. @peterpme, if you're interested in contributing to OC, maybe that project would be worth checking out.

**Comment by peterpme** [comment]
Thank you!

**Comment by alimakki** [comment]
@peterpme you're welcome 👍
