### ISSUE TITLE
Disable DNS Routing

### ISSUE THREAD

**Issue by cpu** [jlund/streisand-discussions#66]
Originally posted by @kamikazechaser in https://github.com/StreisandEffect/streisand/issues/1062:

> I have an AWS instance in Singapore, however DNS queries are being routed to Google (USA) by dnsmasq. This might be This results in slower resolutions. Is it possible to manually disable this behavior on a already running instance and fully stick to the hosts DNS? Tested on latest streisand release (date of issue). Behavior replicated on SSH, Shadowsocks and OpenVPN methods.

**Comment by cpu** [comment]
Hi @kamikazechaser,

>  Is it possible to manually disable this behavior on a already running instance and fully stick to the hosts DNS? 

For an existing server you can edit `/etc/dnsmasq.conf` to change the `server=` lines to whatever DNS server you would like to use.

For a new server you can edit the `global_vars/vars.yml` in the Streisand project directory and change the `upstream_dns_servers` to whatever you would like. Those values will be used for the `/etc/dnsmasq.conf` file on the provisioned servers.

**Comment by kamikazechaser** [comment]
Thanks @cpu,

Managed to use local DNS server instead. I will leave the steps followed here for other users who may want to change theirs too:

Simply comment out the `no-resolv` and the subsequent Google DNS server lines. Restart `dnsmasq` with `sudo /etc/init.d/dnsmasq restart`.

**Comment by cpu** [comment]
Thanks for sharing your approach on-ticket!

**Comment by rorusvan** [comment]
Hi, thanks for the information. And how to change DNS server for Open Connect Cisco ?

**Comment by cpu** [comment]
@rorusvan Since this is a separate question, I answered it in https://github.com/StreisandEffect/discussions/issues/95. Thanks!
