### ISSUE TITLE
digital ocean deployment needs swapfile

### ISSUE THREAD

**Issue by exratione** [jlund/streisand-discussions#67]
Digital Ocean Ubuntu servers don't have a swapfile assigned by default.

Deployment should run something like this:

```
grep -q swap /etc/fstab || {

dd if=/dev/zero of=/swapfile bs=1024 count=256k
mkswap /swapfile
swapon /swapfile
chown root:root /swapfile
chmod 0600 /swapfile

cat >> /etc/fstab <<EOF
/swapfile       none    swap    sw      0       0
EOF

echo 10 | tee /proc/sys/vm/swappiness
echo vm.swappiness = 10 | tee -a /etc/sysctl.conf

}

```

**Comment by cpu** [comment]
@exratione Do you find a DO instance runs out of memory during use/provisioning otherwise?

**Comment by exratione** [comment]
It should not, looking at `free -m` but I'm seeing intermittent issues with a Digital Ocean deployment. Memory is one possibility, but I've yet to earnestly debug things.

**Comment by cpu** [comment]
@exratione Does adding this swap file cause the intermittent issues to go away?

**Comment by exratione** [comment]
So far no. So I'm fine with closing this issue as won't fix, or letting it percolate.

**Comment by cpu** [comment]
@exratione Ok! In that case I think closing this for now is the best bet. It's easy to reopen if there's new information in the future that suggests it might be a useful addition :-) Thanks!
