### ISSUE TITLE
Check streisand server only being used by authorised users

### ISSUE THREAD

**Issue by bobolea** [jlund/streisand-discussions#68]
Hi,

Just wondered what the best way to check that only people you have supplied login details to are using your vpn? Thanks

**Comment by cpu** [comment]
@bobolea I'm not sure I understand the question. How would people you haven't supplied login details to use the VPN services? They all require authentication. Are you asking how to check if a Streisand server has been hacked/accessed without authorization? That's not a question that can be answered in generic terms I'm afraid.

**Comment by bobolea** [comment]
Thanks cpu. Yes you are right it is a very general question, but basically my concern is that I have stood up a vpn server that I dont knowfor sure is secured, although I am sure best practices are being applied. It would be good if some suggestions could be supplied how this could be checked.

**Comment by cpu** [comment]
@bobolea I'm sorry, there's not really an easy answer to that question. I recommend you review the `journalctl` system logs if you're worried about inappropriate access patterns.

You might have better luck posing this question in a general purpose system administration forum like [server fault](https://serverfault.com/). There's nothing particular about Streisand that will make it easier/harder to determine if the server is secured in the general sense of the word.

Good luck!

**Comment by bobolea** [comment]
Hi,

Is there any documentation where the logs are configured for the different vpn's used for Streisand as I would like to be able to periodically monitor these for unauthorised access? I will look at serverfault for the more general question about securing the server. Thanks.

**Comment by nickolasclarke** [comment]
@bobolea We chose to disable logging for many of the services out of privacy concerns. Logging is disabled per service in each of their respective role playbooks, by either setting log files to locations such as `/dev/null`, setting logging levels to silent, or something similar. You'd need to decide which service logging you'd like to re-enable and then make the needed changes to the configuration. The code in the role playbooks are commented very well, so you should be able to skim or search through them and find the changes we've made easily.

**Comment by bobolea** [comment]
Thats great, thanks for the info.
