### ISSUE TITLE
Scalability of Streisand VPN?

### ISSUE THREAD

**Issue by RiteshSingh** [jlund/streisand-discussions#71]
Hi,

Is Streisand scalable to thousands of users (with sufficient server resources of course)?

What will the server need? A high RAM? High CPU? Large Disk Space? Which of the the 3 is most important?

Thanks for your time!

**Comment by cpu** [comment]
Hi @RiteshSingh 

> Is Streisand scalable to thousands of users (with sufficient server resources of course)?

I'm not personally aware of anyone that has tried using Streisand for something at this scale. 

We certainly don't think about this scale of usage when we develop Streisand so while it may work in some capacity it will likely be a bad fit overall. For example, we presently impose an [artificial limit of 20 generated VPN client profiles](https://github.com/StreisandEffect/streisand/blob/master/playbooks/roles/validation/tasks/main.yml#L20:L23) for ~L2TP~, OpenVPN, OpenConnect and WireGuard. You may be better off forking the project and creating a derivative work that emphasizes addressing issues of scale. We're certainly open to reviewing PRs that help Streisand improve the server/client performance if they are non-invasive and don't ratchet up complexity too much.

> What will the server need? A high RAM? High CPU? Large Disk Space? Which of the the 3 is most important?

I think the only way to answer your question is empirically with your own benchmarks.

Thanks for the question!

**Comment by RiteshSingh** [comment]
Dear Daniel @cpu,

Thank you so much for your kind reply.

And thanks for pointing to the limit on VPN client profiles.

Just wanted to ask you what may have been the reason behind limiting the client profiles? Is it for security or performance?

Will a fork without the enforced limit scale to at least hundreds of L2TP clients?

Thank you for your expertise and kind help and explanation.

Ritesh

**Comment by cpu** [comment]
> Just wanted to ask you what may have been the reason behind limiting the client profiles? Is it for security or performance?

Neither. It's just a convenient way to make sure that how we intend Streisand is used when writing the code (by small groups of individuals, not in a large scale setting) matches reality, and to ensure that a typo when choosing how many clients to make (150 instead of 15 for instance) doesn't produce a strange system.

> Will a fork without the enforced limit scale to at least hundreds of L2TP clients?

I don't know. I think the only way to answer your question is empirically with your own benchmarks.

**Comment by alimakki** [comment]
@RiteshSingh, Streisand generates only 1 L2TP client, despite support for multiple clients.
 
Only OpenVPN, Wireguard and AnyConnect (with certificate authentication) will generate multiple client configurations.

You can take a look at the [validation task](https://github.com/StreisandEffect/streisand/blob/master/playbooks/roles/validation/tasks/main.yml) to play with the upper limit of client numbers.

**Comment by cpu** [comment]
@alimakki Oops. You're right. I included L2TP in my earlier comment when it should have been OpenVPN. Edited above to fix.

**Comment by cpu** [comment]
> Just wanted to ask you what may have been the reason behind limiting the client profiles? Is it for security or performance?

As another note, knowing the # of clients is <254 allowed for simple design choices like [using the client number as an IP address offset for the WireGuard clients](https://github.com/StreisandEffect/streisand/blob/e03487d9413276e65a971a6acb23f844b7fbd88b/playbooks/roles/wireguard/templates/server.conf.j2#L11). Allowing more than 254 clients will break the generated IP addresses (e.g. making illegal addresses like `10.192.122.280` in the configs).
