### ISSUE TITLE
How to Forward traffic to ziproxy or Squid?

### ISSUE THREAD

**Issue by hdavy2002** [jlund/streisand-discussions#73]
Unlike this https://github.com/shadowsocks/shadowsocks/wiki/Convert-Shadowsocks-into-an-HTTP-proxy

Is it possible with Streisand? I want to use an http compression like ziproxy with polipo or squid.

Thanks once again guys.

**Comment by cpu** [comment]
Hi @hdavy2002,

I recommend that you take this question to a general purpose system administration forum like [ServerFault](https://serverfault.com/) or the [Ubuntu forums](https://ubuntuforums.org/). Streisand doesn't include zipproxy or Squid and none of the maintainers have experience modifying a Streisand system to include these components. Sorry I don't have any other immediate advice! I'm going to close this issue but folks are free to comment on it if they have insight.

**Comment by hdavy2002** [comment]
Thanks cpu
