### ISSUE TITLE
Expected Time to Completion

### ISSUE THREAD

**Issue by pilleye** [jlund/streisand-discussions#77]
After the initial configuration, the script says,

`Streisand will now set up your server. This process usually takes around ten minutes. Press Enter to begin setup...`

But virtually every time that I've set up a server on DigitalOcean, it's taken around an hour to an hour and a half. Is this problem/misestimate unique to me, DigitalOcean, or is it just an incorrect estimate of the time to setup for everyone?

**Comment by nickolasclarke** [comment]
I havent spun a droplet on DO in a few months, but I suspect that that bit of text simply has not kept up with the pace of change to Streisand, given how much is compiled from source or needs some intensive processing at the moment. We should probably a bit more time to that. Its also highly variable, depending on which provider you are using.

**Comment by alimakki** [comment]
1+ hours for a default seems rather excessive. I suspect latency issues from OPs machine to the DO droplet.
@adityarpillai, if you were to spin up a droplet manually using the DOs panel, then do a localhost install, is it just as slow?

**Comment by cpu** [comment]
This issue has gone stale, closing. Thanks!
