### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by slrslr** [jlund/streisand-discussions#78]
Hello,

when i setup server, my aim is to keep the server silent about my IP using which i am connecting to it - to disable logging and if impossible, prevent writing log file or empty/erase it by a cronjob

is Streisand set to take care about log files produced by the application it installs?

If not, can this be feature that it give user a choice whether it should attempt to disable logging/setup log erasing?

**Comment by nickolasclarke** [comment]
@slrslr the access and connection logs from all services (? @cpu or others please sanity check me here)  are disabled or sent to /dev/null by default. There has been some discussion of allowing or disallowing this logging, and PR's are welcome to bring this feature to the project!

**Comment by cpu** [comment]
> is Streisand set to take care about log files produced by the application it installs?

Streisand makes a best effort to configure services to reduce logging. Speaking personally I haven't spent any time verifying how complete this is, the code/idea predates my involvement. We're certainly over-logging Ansible commands during provisioning (I will try to open a reminder issue when I can verify this).

I wouldn't recommend relying on this being rock-solid and you should perform your own audit of what is/isn't being logged if you want to be sure. Please file issues & PRs for oversights you encounter :-)

**Comment by cpu** [comment]
I believe this question has been addressed. Closing the issue. Thanks!
