### ISSUE TITLE
Double / Triple / Quad bundle for VPN and other issues

### ISSUE THREAD

**Issue by canusuck** [jlund/streisand-discussions#79]
Hello, I have a few questions to help me.
I installed Streisand on 3 of my servers.
How can I create a Wireguard-Wireguard-Wireguard chain or to close everything up?

How can I pick up the chains on the high-speed route. The same is of interest for L2TP / IPsec

During the Wireguard, I constantly update the dns. And there is a leak .. How can I solve this? I would like to take the dns of that country or IP address.

And how can I change the 500 port and which is better to change. To make me less defined as - the availability of VPN Fingerprint.

Sorry for my english.

How best to do this. pls help me

ty u in advance

**Comment by canusuck** [comment]
can u help me?

**Comment by cpu** [comment]
Hi @canusuck 

What you're asking for is far from the intended deployment of Streisand. We don't have any support for these features and do not have time/resources to help you develop them.

I'm afraid you're likely better off forking Streisand to your own repository and starting a new project that can do what you're looking to achieve.

Thanks, apologies that we can't help you in this case.
