### ISSUE TITLE
Streisand fails to enable the WireGuard service on my private Ubuntu 16.04.3 server

### ISSUE THREAD

**Issue by MaikGit** [jlund/streisand-discussions#82]
### Expected behavior:
Streisand starts the Wireguard and DNS masq services
### Actual Behavior:
Streisand fails to start them both and ansible stops to run because of a fatal fail:

[TASK [wireguard : Enable the WireGuard service so it starts at boot, and bring up the WireGuard network interface] ***
fatal: [79.25.195.239]: FAILED! => {"changed": false, "msg": "Unable to start service wg-quick@wg0-server.service: Job for wg-quick@wg0-server.service failed because the control process exited with error code. See \"systemctl status wg-quick@wg0-server.service\" and \"journalctl -xe\" for details.\n"}
...ignoring

TASK [wireguard : Configure DNSMasq to listen on 10.192.122.1:53] **************
changed: [79.25.195.239]

TASK [wireguard : Restart DNSMasq to pick up the new configuration] ************
fatal: [79.25.195.239]: FAILED! => {"changed": false, "msg": "Unable to restart service dnsmasq: Job for dnsmasq.service failed because the control process exited with error code. See \"systemctl status dnsmasq.service\" and \"journalctl -xe\" for details.\n"}
	to retry, use: --limit @/Users/shadow_lugia/Desktop/culo/streisand/playbooks/existing-server.retry

PLAY RECAP *********************************************************************
79.25.195.239              : ok=360  changed=94   unreachable=0    failed=1   
localhost                  : ok=5    changed=0    unreachable=0    failed=0 ]

I have also tried to install the kernel headers issue #500 manually but is shows that i already have the latest headers needed:

[sudo apt-get install linux-headers-`uname -r`
Reading package lists... Done
Building dependency tree       
Reading state information... Done
linux-headers-4.4.0-104-generic is already the newest version (4.4.0-104.127).
linux-headers-4.4.0-104-generic set to manually installed.
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.]

[ ### Ansible Information

* Ansible version: 2.4.2.0
* Ansible system: Darwin
* Host OS: MacOSX
* Host OS version:  10.11.5
* Python interpreter: python
* Python version: 2.7.14

### Streisand Information

* Streisand Git revision: eba9d8c9c7529b7779cb65392d0c6fef0e1f6d35
* Streisand Git clone has untracked changes: yes
* Genesis role: existing-server
* Custom SSH key: False

### Enabled Roles

* Shadowsocks enabled:  True
* Wireguard enabled: True
* OpenVPN enabled: True
* stunnel enabled: True
* Tor enabled: True
* Openconnect enabled: True
* TinyProxy enabled: True
* SSH forward user enabled: True
* L2TP enabled: True
* Configured number of VPN clients: 1]

**Comment by alimakki** [comment]
Hi @MaikGit.

This looks like you're having a troubleshooting issue.

I'm moving this to the Streisand issues list, you can find it [here](https://github.com/StreisandEffect/streisand/issues/1135).

**Comment by MaikGit** [comment]
Thank you! 
I posted it here cause i'm not working on a supported provider so i thought the discussion area was better.
See you there.
