### ISSUE TITLE
Chinese ISPs to block TCP ports 80, 8080, and 443

### ISSUE THREAD

**Issue by aanwark** [jlund/streisand-discussions#84]
I am not sure how credible this [news source](https://www.networkworld.com/article/3245795/sd-wan/china-to-block-sd-wan-and-vpn-traffic-by-jan-11.html) is. However, I am curious to know if it is possible and if there is some backup plan?

**Comment by cpu** [comment]
Hi @denoza,

I'm not sure I understand that news item. They plan to block port 80/8080/443 egressing from China?

**Comment by aanwark** [comment]
How I understand this is that: commercial businesses which use VPN services to connect to their home networks would have to register their VPNs with the authorities. I am not sure how can this be implemented at national level, a lot of Chinese sites are using these ports as well. In addition to that a lot of academic publishers located outside of China also use these ports. However, many of the friends here seem to be panicking after seeing this news item.

**Comment by baimafeima** [comment]
Yesterday, `openconnect` stopped working, not sure if it is related to this.

**Comment by baimafeima** [comment]
Is there anything I can do do get the `openconnect` connection to work again?

**Comment by alimakki** [comment]
@baimafeima is it only OpenConnect that stopped working?

**Comment by alimakki** [comment]
@denoza I found another article with conflicting information: http://www.globaltimes.cn/content/1083918.shtml, although I can't vouch for the trustworthiness of the source.

**Comment by nickolasclarke** [comment]
@alimakki, @denoza's understanding was what I also understood. This should primarily target end-to-end corporate vpn I believe. 

As for the globaltimes....its a state-run tabloid essentially, not a source I would rely on, especially on a technical topic like this.

**Comment by alimakki** [comment]
@nickolasclarke Appreciate the input. I'm largely ignorant of the region and its subtleties.

**Comment by nickolasclarke** [comment]
@alimakki of course!

**Comment by nopdotcom** [comment]
I'm going to close this specific bug because it's tied to an iffy news story, and we can get more timely information by experimentation; it just becomes another part of the documentation, then.
