### ISSUE TITLE
Meltdown mitigation with Lindode

### ISSUE THREAD

**Issue by baimafeima** [jlund/streisand-discussions#88]
I was informed by Linode that they are undergoing maintenance to mitigate the vulnerabilities caused by Meltdown (and later Spectre). According to Linode: 

> To further protect your Linode, we strongly recommend that you verify it is configured to boot using our latest kernel, which includes patches to help address these vulnerabilities. If your Linode's Configuration Profile is set to utilize our latest kernel, your kernel will automatically be updated upon rebooting.

I checked in Edit Configuration Profile > Boot Settings > Kernel and the streisand server is automatically set to use GRUB2 under the kernel settings. Shall I make any changes there and if yes, which ones or leave it with the default parameters, i.e. GRUB2?

**Comment by cpu** [comment]
@baimafeima GRUB2 is the only kernel option that is known to work with Linode & Streisand. Using a different kernel option is liable to break Wireguard and other services dependent on the kernel & headers.

Your server will automatically install kernel updates and should receive the same meltdown/spectre patches.

**Comment by baimafeima** [comment]
@cpu Just now I got the following information from Linode: 

> If you are using a kernel provided by your distribution and have your kernel option set to “GRUB 2” in the Linode Manager, then you will need to update using your distribution’s package manager. Details can be found in our documentation, here:
> 
>    > https://linode.com/docs/platform/meltdown_statement/#meltdown
> 
> You can check your kernel version after updating wit the following command:
> 
>    uname -r

If I understand Linode correctly, I would still have to upgrade the kernel manually. As Streisand was set up automatically via a script, I am not sure how to upgrade the kernel manually without affecting my Streisand installation. In fact, I don't have much experience with server configurations at all. Could you provide more information what I (or many others in this case who are having their servers with Linode) should do?

**Comment by cpu** [comment]
> If I understand Linode correctly, I would still have to upgrade the kernel manually. 

That would be true on a generic Ubuntu server but not on a Streisand server. Part of the Streisand provisioning process [enables automatic security updates](https://github.com/StreisandEffect/streisand/blob/master/playbooks/roles/common/tasks/main.yml#L82:L91) using [unattended-upgrades](https://help.ubuntu.com/community/AutomaticSecurityUpdates#Using_the_.22unattended-upgrades.22_package).

>  Could you provide more information what I (or many others in this case who are having their servers with Linode) should do?

I mentioned before:

> Your server will automatically install kernel updates and should receive the same meltdown/spectre patches.

This remains true :-) You don't have to do anything. The updates will be installed without any user intervention and your server will automatically reboot itself to apply the update.

**Comment by baimafeima** [comment]
Thanks a lot for the clarifications. This sounds great!
