### ISSUE TITLE
Azure VM size inefficient

### ISSUE THREAD

**Issue by leninalive** [jlund/streisand-discussions#90]
I think that Streisand script chooses VM size in Azure in too greedy manner. Script selects cheapest size A0 in Basic favor, and that favor impacts network bandwidth limiting it to only 10 Mbps in both ways.
While the Standard_A0 price is being higher for only 11% ($15 vs. $13.2 per month), it comes with 100 Mbps bandwidth limit.

**Comment by cpu** [comment]
@leninalive I'd be receptive to a pull request updating the Azure VM size.

**Comment by cpu** [comment]
Going to close this issue for now. I'm not personally able/interested in supporting Azure and since this has been the only complaint I think its an issue that can rest until someone who uses Azure submits a PR. Thanks!
