### ISSUE TITLE
FEATURE REQUEST: streisand mesh

### ISSUE THREAD

**Issue by zenny** [jlund/streisand-discussions#91]
Opened this as suggested by @cpu  at https://github.com/StreisandEffect/streisand/issues/1159 which is about creating a mesh network of multiple instances of streisand deployment in different geographical locations. Thanks.

**Comment by nopdotcom** [comment]
Thanks for opening this here.

What functionality do you want from a mesh? Exit IP mobility?

**Comment by cpu** [comment]
I'm going to close this issue. It's gone stale without reply and the complications of mesh networking / multiple server coordination are well outside of what Streisand can support. Thanks!
