### ISSUE TITLE
Generate additional OpenVPN direct client profiles?

### ISSUE THREAD

**Issue by wicknet** [jlund/streisand-discussions#92]
Wonderful software that does everything it claims. Couldn't be happier.

Have handed out the 5 pre-built combined profiles for OpenVPN (after suitably renaming them) to family and friends, so they are able to connect even in a super-restrictive work environments. 

All good till this point.

Are there built-in commands to generate more "unique" ovpn profiles? Trying to avoid recycling the 5 profiles that are already in use. When I was using OpenVPN road-warrior setup from Nyr, one could generate as many client profiles as needed.

Thanks for your fine work.

**Comment by cpu** [comment]
Hi @wicknet,

> Are there built-in commands to generate more "unique" ovpn profiles? Trying to avoid recycling the 5 profiles that are already in use. When I was using OpenVPN road-warrior setup from Nyr, one could generate as many client profiles as needed.

Unfortunately not at this time. Streisand only generates the profiles once, at the time of provisioning. To have more profiles you will have to create a new Streisand instance and migrate existing clients to the profiles from the new instance.

Apologies, I know that's a crummy experience. Supporting migration of data/users between instances is on our mind. Similarly having support for adding more users after the fact would be a great asset. Both will be fairly substantial undertakings.

https://github.com/StreisandEffect/discussions/issues/30 is probably the best issue to follow for progress in this space. I'm going to close this issue for now to consolidate discussion on #30.

Thanks!
