### ISSUE TITLE
Does this script provides service like fastssh.com?

### ISSUE THREAD

**Issue by draft1** [jlund/streisand-discussions#94]
I just want to setup one, not sure if this script are capable of?

Thanks!

**Comment by cpu** [comment]
Hi @RoldanLT,

Yes, by default Streisand creates a `forward` user and a SSH keypair that can be used for port forwarding. The generated documentation in your Streisand gateway explains how to use this user with SSH on Linux/mac and with PuTTY on Windows.

Hope that helps!
