### ISSUE TITLE
Consider allowing Streisand servers to update to new Streisand version in-place

### ISSUE THREAD

**Issue by 459217974** [jlund/streisand-discussions#96]
Now if I want to update to the latest version, I have to reinstall, so that some of my personal configuration is gone.

**Comment by cpu** [comment]
> Now if I want to update to the latest version, I have to reinstall,

@459217974 I'm not sure I understand, can you expand on this? You wanted to update to the latest version of what? Streisand? A specific Streisand service (OpenVPN, shadowsocks-libev, etc)?

**Comment by 459217974** [comment]
I mean update the Streisand

**Comment by cpu** [comment]
Aha! That makes sense.

I agree that it's a poor user experience to have to reinstall from scratch & reconfigure clients to get new Streisand features. We've talked a little bit about this in https://github.com/StreisandEffect/discussions/issues/30 and I recommend subscribing to that issue for more updates.

It's something we want to fix and we are making steps towards that goal but it will be some time before we have laid the ground work required.

Thanks for your patience! I'm going to close this issue for now to consolidate discussion on issue #30.

**Comment by 459217974** [comment]
got it. thanks a lot
