### ISSUE TITLE
Q: Any relevance of vpn_clients to L2TP/IPSec?

### ISSUE THREAD

**Issue by phlbnks** [jlund/streisand-discussions#99]
Just wondering - does the vpn_clients setting have any relevance to L2TP/IPSec connections? 
No my area of expertise but I'm guessing not as there's only a single mobileconfig file / PSK / password. Can anyone confirm? There's no hidden limit to concurrent use of the dredentials or something is there?
If wanted / needed - am I right thinking I edit `/etc/ppp/chap-secrets` with new rows following the `client - server - secret - IP addresses` pattern to create distinct users?

Thanks!

**Comment by alimakki** [comment]
Hi @emirpprime,

To answer your questions:

> does the vpn_clients setting have any relevance to L2TP/IPSec connections?

The vpn_clients currently only affects the following:

 - OpenVPN
 - OpenConnect
 - WireGuard

> No my area of expertise but I'm guessing not as there's only a single mobileconfig file / PSK / password. Can anyone confirm? There's no hidden limit to concurrent use of the dredentials or something is there?

 As of right now, you are correct that there is a single user configured for L2TP/IPsec. 

I do not believe there is any limit on concurrent users for L2TP/IPsec (I could be wrong becuase I've never actually used L2TP/IPsec), but there are ones for the ones mentioned above.

>If wanted / needed - am I right thinking I edit /etc/ppp/chap-secrets with new rows following the client - server - secret - IP addresses pattern to create distinct users?

that looks about right to me, you'll be adding new username/password combo, but the PSK will remain static for all users.

**Comment by phlbnks** [comment]
Great - thanks for the clarification @alimakki
